//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlEstudiantesUNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asignaturas()
        {
            this.estudianteAsignatura = new HashSet<estudianteAsignatura>();
            this.estudianteNotas = new HashSet<estudianteNotas>();
        }
    
        public long idAsignatura { get; set; }
        public string codigoAsignatura { get; set; }
        public string nombreAsignatura { get; set; }
        public Nullable<long> idPadre { get; set; }
        public Nullable<bool> activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudianteAsignatura> estudianteAsignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estudianteNotas> estudianteNotas { get; set; }
    }
}
