//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlEstudiantesUNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public long idBitacora { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public string proceso { get; set; }
        public string formulario { get; set; }
        public Nullable<System.DateTime> fecha_transaccion { get; set; }
    }
}
