//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlEstudiantesUNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudianteAsignatura
    {
        public long idEstudianteAsignatura { get; set; }
        public Nullable<long> id_estudiante { get; set; }
        public Nullable<long> id_asignatura { get; set; }
        public Nullable<long> id_docente { get; set; }
        public string horario { get; set; }
        public Nullable<long> id_periodo { get; set; }
        public Nullable<double> parcial_uno { get; set; }
        public Nullable<double> parcial_dos { get; set; }
        public Nullable<double> convocatoria { get; set; }
        public Nullable<double> nota_final { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion { get; set; }
        public Nullable<bool> aprobado { get; set; }
        public Nullable<bool> completado { get; set; }
        public Nullable<long> id_grupo { get; set; }
    }
}
