//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlEstudiantesUNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudianteGrupo
    {
        public long idEstudianteGrupo { get; set; }
        public Nullable<long> id_estudiante { get; set; }
        public Nullable<long> id_grupo { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual catalogos catalogos { get; set; }
        public virtual estudiante estudiante { get; set; }
    }
}
