//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlEstudiantesUNI
{
    using System;
    using System.Collections.Generic;
    
    public partial class localidad
    {
        public long idLocalidad { get; set; }
        public Nullable<long> id_padre { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
